### ISSUE TITLE
Permissions View MVP

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1232]
The MVP features:
- Display the access policy as a table
- Ability to change the permission of each access rule
- Ability to change the subject of each access rule
- Add new access rule (by user or group subject)
- An overall public/private toggle that toggles the public-read access rule
- Search for person or group via the D1 accounts service
- Remove access rule via an X delete button

Features to be added after the MVP:
- Sort the table by each column
- Search for a person via the ORCID search service

**Comment by vchendrix** [comment]
Does this include support for manging the access policy for data packages?

**Comment by laurenwalker** [comment]
Yes

**Comment by mbjones** [comment]
The inability to share permissions within a lab group is a blocker to effective use of the tool.  Another group using the KNB is struggling with this now. I increased the priority on this to Critical.

**Comment by laurenwalker** [comment]
I'll try to get it worked in as soon as we can. May have to reprioritize some other high priority features if this is truly critical.

**Comment by amoeba** [comment]
Just a little update here: @laurenwalker and I chatted on Slack this week about putting together a wireframe for this and I spent some time today working one up. See https://www.figma.com/file/rNgsCNoNFPRtErX5tLKudg/Permissions-View-MVP?node-id=1%3A2 (it's interactive if you press Play).

Some high-level things:

- I went with the concept of "Share" as it's an active verb and familiar to the broadest audience. As opposed to "Access" or "Permission".
- This UI is optimized for applying the same set of access rules to all members of a package which should be the most common use case by far. Setting individual access rules is hidden behind a hover to avoid UI clutter.
- The Share Modal looks mostly like the portal share modal but is different mainly because I forced myself not to copy it verbatim.

@laurenwalker @csjx do you wanna touch base next week an iterate on this over a video call? I can find a shared time slot but let me know if you have any preferences.

**Comment by mbjones** [comment]
I think that using the Share layout and design from the portal settings as closely as possible would help reinforce usage patterns and make it easier to learn. Plus, it is largely doing the same thing, but just being applied to a different object (either a data package or a single data object). So, couldn't we turn the nicely designed Share section from the portal into a reusable modal that could be called up in place of your modals?

<img width="1542" alt="share-modal" src="https://user-images.githubusercontent.com/766407/87350298-220c6480-c504-11ea-8c22-f1b292192b81.png">

I agree with your 'default to the whole package' approach. It would be good if it were clearer that the package-level rules will also apply to objects unless an object-specific policy is added.

**Comment by amoeba** [comment]
> So, couldn't we turn the nicely designed Share section from the portal into a reusable modal that could be called up in place of your modals?

Yep, that's exactly what I was thinking. My design just differs in some ways for fun but these UIs need to be 100% identical IMO.

> It would be good if it were clearer that the package-level rules will also apply to objects unless an object-specific policy is added.

Good point. I think we might be able to use a combination of iconography and text to make it more clear. Though I think having the rules apply to the entire package will be very intuitive to people.

**Comment by amoeba** [comment]
Just made some updates along the lines of my latest. Shared icons are used to link things visually and text is used to make it clear what's being changed.

**Comment by laurenwalker** [comment]
Thanks Bryce, this looks really good. I agree with Matt that we should reuse the design and language we already have implemented (e.g. you changed "Is owner" to "Manage" but I think we want to keep "Is owner".) We've gone through several design reviews in our Portal Editor meetings of that view already so we shouldn't change anything unless it's obvious something isn't working well right now.

- > I went with the concept of "Share" as it's an active verb and familiar to the broadest audience. As opposed to "Access" or "Permission".

I agree with this and it's what we have done in the portal editor. Note that the name of the view/button is configured in the AppModel (it defaults to "Sharing options"), so we will want to use that in the view:

https://github.com/NCEAS/metacatui/blob/2d5b18d100f3d4a0067ecfad034fc5b786efdb3c/src/js/models/AppModel.js#L756

- I like using the share/fork icon in the DataItemView, since it has minimal real estate already. I think we should allow that icon to be configured in the AppModel as well (e.g. `accessPolicyIconName`)

- In your wireframes I see that the Share icons only show up when the row is hovered on. I like how this keeps things uncluttered but I wonder if people will miss it? I guess I'd have to see it in action.

- I'm wondering if we should remove the "Public" toggle that displays directly in each row since we have the Public toggle in the AccessPolicyView now. I think it could be confusing to have the toggle in two places.

- I like the sentence that specifies exactly what is being changed "Changes here apply to all two files.."

- I noticed that you moved the Status column to the left side of the table. I think we want to keep it where it is now. Particularly since the status of the files correspond to the "Describe" button (they are both yellow when file metadata is missing), we should probably display them next to each other.

**Comment by amoeba** [comment]
Hey @laurenwalker , thanks for taking a look. Apologies about the confusion over how much mockups differed from the established UI. That was just for fun.

> In your wireframes I see that the Share icons only show up when the row is hovered on. I like how this keeps things uncluttered but I wonder if people will miss it? I guess I'd have to see it in action.

Right. I'm usually not a fan of hiding UI behind hover and I think we might prefer to have it always who.

> I'm wondering if we should remove the "Public" toggle that displays directly in each row since we have the Public toggle in the AccessPolicyView now. I think it could be confusing to have the toggle in two places.

I think that might look and work great to remove the per-DataItem checkboxes, yeah. Having the functionality in two places may be confusing as you say and hiding it behind a click and a modal should be fine because it should be an uncommon action.

I'll get started on implementing the core of this functionality this week.

**Comment by laurenwalker** [comment]
Sounds great, thanks

**Comment by laurenwalker** [comment]
Any updates on the progress of this?

**Comment by amoeba** [comment]
None yet, but I have time set aside for this this week.

**Comment by amoeba** [comment]
Initial implementation done in https://github.com/NCEAS/metacatui/commit/99af8230ab43b723a37db396031414f0b7a5a651. I started by getting public/private toggling working for the entire package and building out the modal dialog which also has a public/private toggle. Works but has some UI tweaks to hammer out. Biggest thing to start on next week is hooking in the existing `AccessPolicyView` so individual permissions can be edited.

**Comment by amoeba** [comment]
Basic and not-quite complete implementation done as of https://github.com/NCEAS/metacatui/commit/6dddbbe347c573663311000624fcdc91bbe57d24.

What we have:

- iOS-style public/private toggles in the package table like I mocked up. Basically a condensed version of the one inside the AccessPolicyView
- Share buttons for the metadata and data (not resource map or for the whole package) hooked into a modal dialog that lets you set public/private and edit access policies

There are a few things I wanna tweak still on the above:

- The modal currently has Cancel and Save buttons. I need to think about the best behavior here. Should it be Close and Save? Should Cancel still be there and should Save close the modal or turn into a Close button when the Save succeeds?
- In the package table, the cell widths are really optimal. Not sure what's up there but the public/private toggle column is way too wide
- I think the modal should be bigger when there's enough screen real estate
- Improve text at the top of the modal "Give others access to view, edit, and share this data file" like I showed in the mockup
- Error testing

I'll take a look at these tomorrow. @laurenwalker do you wanna take a peek and let me know how it's looking like we talked about on our dev call today? All my changes are synced with `origin/feature-permissions-view-mvp`.

**Comment by mbjones** [comment]
awesome, @amoeba ! When it makes sense, can you drop some screenshots in here of it as-implemented for a quick review?

**Comment by laurenwalker** [comment]
Thanks Bryce, I will take a look soon

**Comment by amoeba** [comment]
Hey @mbjones, now works:

Shot showing the new Public and Share columns. Clicking the Public toggle toggles public-read on and off and animates like an iOS toggle.

<img width="971" alt="Screen Shot 2020-12-04 at 1 55 01 PM" src="https://user-images.githubusercontent.com/563/101223513-accb3880-3638-11eb-863e-63d248726506.png">

Shot showing the modal dialog that pops up when you click the Share button, shown in context with the data package view behind it:

<img width="790" alt="Screen Shot 2020-12-04 at 1 55 12 PM" src="https://user-images.githubusercontent.com/563/101223526-b0f75600-3638-11eb-855a-5aa2b5a61c24.png">

GIF showing toggling the public/private toggle and opening the Share modal:

![2020-12-04 13 56 35](https://user-images.githubusercontent.com/563/101223532-b359b000-3638-11eb-8f3e-c92ef6cf7179.gif)

**Comment by laurenwalker** [comment]
Looks really great so far. My thoughts from my initial review, to be discussed with team and addressed for MVP:

[ ] Not clear that share icon is a button
[ ] Get rid of Public toggle? Or combine with Share button
[ ] Toggle doesn't send an instant save but the modal "Save" button does - confusing?
[ ] Public toggle is hard to see with white background
[ ] Share permissions for the top-level (metadata) - should they apply to the other files as well? (maybe this is beyond the MVP)
[ ] Add tooltip to disabled share buttons to explain why it's disabled
[ ] Increase height of modal window
[ ] Save button should close modal after save is complete (#1276)
[ ] New files should inherit access policy from package instead of repo/app default (Related to #1640)
[ ] Probably beyond the MVP - but permissions view for non-EML packages - Display in MetadataView? Load non-EML in a minimal editor?

**Comment by amoeba** [comment]
Knocked out a few of these just now:

- [x] Not clear that share icon is a button
- [x] Get rid of Public toggle column
- [x] Add tooltip to disabled share buttons to explain why it's disabled
- [x] Increase height of modal window
- [x] Save button should close modal after save is complete (#1276)
- [x] Disable cancel button while saving

I'll work on this tomorrow:

 - [ ] Update RM access policy when metadata policy is updated

**Comment by amoeba** [comment]
Added a method where any updates to the metadata's access policy get applied to the resource map too. Includes basic error handling. Committed in f219fd77d638b493f368068f5440ef0717755930. Here's my commit message:

> I'm kind of inventing a system here but I expect we'll want to change it in future iterations. Rather than refactor the AccessPolicyView to support editing access policies for more than one object or building a new View that can do this, I just built a toggle on the AccessPolicyView to broadcast any changes broadcasting the change and handing off control to the DataPackage class to  handle saving and error handling.

We effectively pre-flight the broadcasted change to the resource map by guarding the UI behind an access check so it's very likely the sysmeta update on the resource map will succeed (barring normal request errors). That's why I thought I could get with with what is basically a background request and with a basic error UI. Let me know what you think @laurenwalker.
