### ISSUE TITLE
Add the Portals View to the DataONE theme

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1244]
Currently, portals can only be viewed in the non-DataONE themes. It should be a fairly simple alteration to get the portals viewable in the DataONE theme, too. The primary difference is that the CN API is used instead of the MN API - this needs some testing to make sure everything works smoothly. We also need some minor alterations to remove the Edit button.

**Comment by laurenwalker** [comment]
Hi @robyngit - I reviewed this branch today and it looks great. I pointed my local MetacatUI to search.dataone.org so I could test the display of our production portals and compare them to the display on their member node (primarily Arctic portals). Some issues:

- [ ] The DBO portal has an image in the markdown that displays on the MN:
![Screen Shot 2020-06-15 at 4.03.34 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/186ccdb8-f78a-4aca-baa9-d728f500a3a2)

but in the DataONE theme, the `img` `src` is set to `(unknown)`:

![Screen Shot 2020-06-15 at 4.07.45 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/f31c2fc3-9435-4f0b-9ef4-df6fc4a9c632)

The same thing happens on the `permafrost` portal, but some portals display images just fine.

- [ ] The temporal coverage bar chart has the dataone orange color as a border on each bar:
![Screen Shot 2020-06-15 at 4.12.35 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/0d428c0d-31ff-45bd-8825-da9f68c4b2be)

- [ ] There's also a funny issue where sometimes the portals in the DataONE theme show more than the Arctic theme, even though all datasets in the portal are from the Arctic MN, so the dataset list should be identical. I will investigate into this, too, since it might be a larger issue than MetacatUI.

Also note that when I merged the master branch into your feature branch, it was updated to the new configuration: https://nceas.github.io/metacatui/install/#for-metacatui-v2120-and-later

**Comment by robyngit** [comment]
Good catches! Fixed the first two (see commit 98e42d5). I can't immediately think of a reason behind the last issue, but I'll take a look.

**Comment by laurenwalker** [comment]
Thanks for the fixes! I looked into the issue about the dataset collections being different between the MN and CN and found that it's due to issues with some objects not indexing or syncing correctly to the CN. So I'll bring this up at our dev meeting on 6/18 and close this ticket.

The `feature-dataone-portals` branch is now merged into the `dev-2.13` branch.
