### ISSUE TITLE
Move MN repository profiles from the UserView to PortalView

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1261]
When the user navigates to /profile or /profile/node-id, we want to display the node "profile" using the new PortalView instead. There won't be a portal document associated with this portal. 

- [x] The collection query should use `datasource:urn:node:{id}`

- [x] The UserView should construct a PortalModel using the info from the node info document, and the PortalView will use that populated model to display "Data" and "Metrics" sections. 

- [x] The logo and repository name from the node info document will be used in the portal header. 

- [x] The Edit Portal button should be removed.

- [x] The /profile views will only have a metrics tab

- [x] The /profile view in the DataONE theme should show all the stats for the CN.

- [x] The /profile view in other themes should show all the stats for the MN/repo

- [x] (low priority) If the repository is not a DataONE MN, then /profile should hide the paid features (the 3 metrics charts and metadata quality chart)

Priority for 2.9.0 is:
- [x] The /profile view in other themes should show all the stats for the MN/repo

Then we can roll out the MN profiles and CN profile in the DataONE theme in 2.10.0
