### ISSUE TITLE
Semantic search in portals

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1653]
Portals collection queries can currently be built with filters based on our `sem_annotation` field and portal data searches can search for datasets based upon the field but it's currently limited to manually entering URIs in both cases. This means only experts in our system can really use the feature at the moment.

A much more powerful and user-friendly way to expose semantic search in both (1) portal data search and (2) portal collection query building would be to help the user to find the right term(s) by more advanced means such choosing a value (or values) in a tree browser and/or free-text search against a set of terms, an ontology, or a set of ontologies.

I think we need to discuss a bit what type of scope we might target here before we do any work and follow that with some mock-ups.

- [x] Enhance semantic search in custom portal data search filters
- [x] Enhance semantic search in portal query builder

Edit 20200126: @robyngit informed me that this has been hooked into the query builder and shows up when a BioPortal API key is set. So we might just need to hook this into the portal data search.

**Comment by robyngit** [comment]
Hey @amoeba, if I understand what you're proposing correctly, this feature is already implemented in the Query Builder. However, it only works on the ADC portal builder because it requires a bio-portal API key to be configured (`MetacatUI.AppConfig.bioportalAPIKey`). If one is not configured, like on the KNB or DataONE MetacatUI, then it reverts back to the simple text input where you would need to manually enter a URI, like you pointed out.

> choosing a value (or values) in a tree browser

<img width="430" alt="Screen Shot 2021-01-26 at 09 24 54" src="https://user-images.githubusercontent.com/26600641/105857983-d78e9900-5fb8-11eb-8401-53bdf770528e.png">

> free-text search against a set of terms

<img width="430" alt="Screen Shot 2021-01-26 at 09 25 16" src="https://user-images.githubusercontent.com/26600641/105857999-da898980-5fb8-11eb-9665-a497d0568806.png">

Is this what you meant, and is it showing up for you when you build a query through the ADC? Were you imagining other ways that we could improve this?

I don't think we're using this view for the custom portal search filters yet

**Comment by amoeba** [comment]
ah cool, thanks @robyngit. I had missed that as I was only testing on test.arcticdata. That's totally what we were thinking. I'll update the issue text to reflect this. We would like to also see it exposed as a custom portal search filter so I'll leave this open to track that work.

**Comment by rushirajnenuji** [comment]
We demoed this feature with the Salmantics team, here are some of the enhancements suggested:

- [ ] Current portal semantic search filter shows dual search text box, updating the design to be clearer to the user.
- [ ] Show currently selected annotation filter in the div above to indicate that the datasets listed are filtered based on selection. 
- [ ] Review the changes

**Comment by amoeba** [comment]
We touched base on this during today's salmantics call and @rushirajnenuji is going to try to wrap up next week. At that point we can take a look as a group and if there's any more changes, I'll probably take a look since I have the cycles.

**Comment by amoeba** [comment]
This is partly done but I'm still working on making making this work in the portal editor (where it only half works right now).

**Comment by amoeba** [comment]
I've refactored most of the original implementation in response to feedback in #1842. I'm now working on addressing @laurenwalker 's [comment](https://github.com/NCEAS/metacatui/pull/1842#issuecomment-944446742):

> I think for this first release it would be nice to have only Free Text filters enabled for annotations filters so that users aren't confused about what to do for dropdowns and toggles

I mistakenly dropped a comment asking for feedback in https://github.com/NCEAS/metacatui/issues/1900 and @robyngit replied with some great feedback in a [comment](https://github.com/NCEAS/metacatui/issues/1900#issuecomment-1011329112). I'm going to do one more pass to address those comments.

**Comment by amoeba** [comment]
Hey @laurenwalker, the feedback you and @robyngit have given is reflected in https://github.com/NCEAS/metacatui/pull/1842 which I've re-opened. It's ready for another review, see my comment in https://github.com/NCEAS/metacatui/pull/1842#issuecomment-1013592435.
