### ISSUE TITLE
usability issues in the People section

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#198]
In the People section, there are several issues that make it hard to use and not obvious what to do. 
 I start by filling in my Creator info. After that:

- [ ] it is not obvious how I add another creator.  This needs to be very clear.  I can't see how to do it. (#225)
- [ ] It is not obvious that a Contact role must be created. Make it clear. Even better, by default create a new empty party block for the first creator. -- This is a usability issue that we will keep collecting feedback on once 2.0.0 RC 1 is deployed.
- [ ] Once a contact is filled in, its not obvious how to create another (it disappears from the dropdown) - also #225
- [ ] Once I've filled in my details once, I shouldn't have to enter them again (particularly in the same dataset, but really across all of my or other data sets -- see elaboration in issue #175) - #227
    - [ ] In particular, lookup my ORCID from my email, or look up my name and contact from my ORCID (#221)

**Comment by csjx** [comment]
Hi @mbjones @laurenwalker - I agree, we definitely need to make this more usable. Although, I'm wondering how doable this is for 2.0.0? Should this be a top priority for 2.1.0, or do you want to tackle it by today/tomorrow?

**Comment by csjx** [comment]
We're going to wait for some more feedback from other testers before making a decision about the People section.  We can add a `Add Party` button, and we can explicitly show that a `Contact` is required, but we actually create a contact from the first `Creator` if one isn't made.  Re-entering information is an issue that we discussed during the mockup design phase and explicitly pushed it to a later release. Needs discussion.

**Comment by laurenwalker** [comment]
Created a new ticket for 

> "In particular, lookup my ORCID from my email, or look up my name and contact from my ORCID"

#211
