### ISSUE TITLE
Improve data layer searchability and categorization 

### ISSUE THREAD

**Issue by nikitamaia** [NCEAS/metacatui#2279]
As the number of data layers in PDG grows, we need a way to categorize and search so users can find what they need.

Sub tasks:

- [x] [Data layer categorization](https://github.com/NCEAS/metacatui/issues/1773)
- [x] [Data layer search](https://github.com/NCEAS/metacatui/issues/1796)
- [x] [Layers list polish](https://github.com/NCEAS/metacatui/issues/2277)
