### ISSUE TITLE
Implement zooming to predefined regions [EPIC]

### ISSUE THREAD

**Issue by nikitamaia** [NCEAS/metacatui#2281]
Add preconfigured region and data layer combinations to help users get started exploring immediately

- [x] [Zoom to a predefined area](https://github.com/NCEAS/metacatui/issues/2275)
- [x] [Zoom to a predefined area with data layers enabled](https://github.com/NCEAS/metacatui/issues/2276)
- [ ] [Zoom-to story view](https://github.com/NCEAS/metacatui/issues/2385)
