### ISSUE TITLE
Eng roadmap and design tracking for viz [EPIC]

### ISSUE THREAD

**Issue by yvonnesjy** [NCEAS/metacatui#2386]
- [ ] [Save the current Cesium config as a link for sharing](https://github.com/NCEAS/metacatui/issues/1806)
- [ ] Summary mode viz pipeline and FE design
- [ ] [Initial steps toward easier theming in cesium maps & portals](https://github.com/NCEAS/metacatui/issues/2370)
- [ ] [fix responsive use of portals with cesium map views](https://github.com/NCEAS/metacatui/issues/2230)
